version: '3.8'

services:
  db:
    image: postgres:15.0
    container_name: warehouse_db
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - warehouse-network

  app:
    build: .
    container_name: warehouse_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - warehouse-network

volumes:
  db-data:

networks:
  warehouse-network:
    driver: bridge
