"""Update order created_at to use timezone-aware datetime

Revision ID: 0d42a5a0f12b
Revises: 3b4bab72771d
Create Date: 2024-09-23 10:30:06.488874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d42a5a0f12b'
down_revision: Union[str, None] = '3b4bab72771d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
